I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 70, in script
    e "You've created a new Ren'Py game."
Exception: Sayer 'e' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 70, in script
    e "You've created a new Ren'Py game."
  File "C:\Users\kyle\Ren'Py\renpy\ast.py", line 566, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\kyle\Ren'Py\renpy\ast.py", line 484, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'e' is not defined.

Windows-post2008Server-6.2.9200
Ren'Py 6.18.1.670
Beacon 0.0
